### PR TITLE
[1] Bump data-schema to v15

### PR DESCRIPTION
**Pull request by tkyi**
Pull in `eventId` as a field in builds

### CODE REVIEW

**Comment by FenrirUnbound** [comment]
What impact does this have on the modules that extend this class?

**Comment by tkyi** [comment]
@FenrirUnbound We're going to need to update data-schema in a bunch of different packages. This is the first PR we will need to make

**Comment by FenrirUnbound** [comment]
If we release this change, will it break the modules that extend this class?

**Review by FenrirUnbound — APPROVED** [review]
👍 

Looks legit to me

pikachu and togepi sharing a drink - imgur

**Comment by tkyi** [comment]
It would definitely break the Screwdriver API
Anytime there are mismatched npm module versions, like in this PR build: https://cd.screwdriver.cd/pipelines/613a05120b3c7166749d049b549d5edece076cdf/build/34029902d4461a565796818dcab3036a4b658db2

This PR should be merged after https://github.com/screwdriver-cd/screwdriver/pull/336

**Comment by d2lam** [comment]
@tkyi  I think @FenrirUnbound  means whether this will break anything that is using this package - like datastore-dynamodb, etc. If it does, then we should probably its bump major version

**Comment by tkyi** [comment]
@d2lam This particular data-schema version only adds an optional field (eventId) to builds. It shouldn't break anything using this package.

**Comment by tkyi** [comment]
I'll bump minor so we can make sure all other modules that depend on datastore-base get the new datastore-base with the new data-schema

**Pull request merged**
